import type { ProcessorStatusEntry } from '../../../shared/messages.ts';
import { t, type Locale } from '../../i18n.ts';

export function pluginCopy(locale: Locale) {
  return {
    title: t(locale, 'pluginsTitle'),
    lead: t(locale, 'pluginsLead'),
    builtInLabel: t(locale, 'builtInActions'),
    builtInNote: t(locale, 'builtInActionsNote'),
    installed: t(locale, 'pluginsInstalled'),
    store: t(locale, 'pluginsAvailable'),
    actionsLabel: t(locale, 'pluginActionsLabel'),
    install: t(locale, 'pluginInstall'),
    activate: t(locale, 'pluginActivate'),
    uninstall: t(locale, 'pluginUninstall'),
    active: t(locale, 'pluginActive'),
    disabled: t(locale, 'pluginDisabled'),
    unavailable: t(locale, 'pluginUnavailable'),
    emptyInstalled: t(locale, 'pluginsEmpty'),
    emptyStore: t(locale, 'pluginsStoreEmpty'),
    searchPlaceholder: t(locale, 'pluginSearchPlaceholder'),
    searchEmpty: (query: string) => t(locale, 'pluginSearchEmpty', { query }),
    explore: t(locale, 'pluginsAvailable'),
    usedBy: (count: number) => t(locale, 'pluginUsedBy', { count }),
    confirm: t(locale, 'pluginUninstallConfirm'),
    details: t(locale, 'pluginDetails'),
    settings: t(locale, 'pluginSettings'),
    saveSettings: t(locale, 'pluginSettingsSave'),
    settingsHint: t(locale, 'pluginSettingsHint'),
    installPackage: t(locale, 'pluginInstallPackage'),
    installing: t(locale, 'pluginInstalling'),
    installSuccess: t(locale, 'pluginInstallSuccess'),
    installFailed: t(locale, 'pluginInstallFailed'),
    replaceConfirm: t(locale, 'pluginReplaceConfirm'),
    replaceAction: t(locale, 'pluginReplace'),
    cancel: t(locale, 'cancel'),
    processorsTab: t(locale, 'processorsTab'),
    processorsLead: t(locale, 'processorsLead'),
    processorsEmpty: t(locale, 'processorsEmpty'),
    processorsRefresh: t(locale, 'processorsRefresh'),
    processorEventsLabel: t(locale, 'processorEventsLabel'),
    processorAllEvents: t(locale, 'processorAllEvents'),
    processorTimeout: t(locale, 'processorTimeout'),
    processorPriority: t(locale, 'processorPriority'),
    processorMetricsLabel: t(locale, 'processorMetricsLabel'),
    processorTest: t(locale, 'processorTest'),
    processorTestOk: t(locale, 'processorTestOk'),
    processorTestFailed: t(locale, 'processorTestFailed'),
    processorTestDuration: t(locale, 'processorTestDuration'),
    metricLabels: {
      calls: t(locale, 'processorMetricCalls'),
      successes: t(locale, 'processorMetricSuccesses'),
      failures: t(locale, 'processorMetricFailures'),
      timeouts: t(locale, 'processorMetricTimeouts'),
      skippedCircuitOpen: t(locale, 'processorMetricSkippedCircuitOpen'),
      skippedOverloaded: t(locale, 'processorMetricSkippedOverloaded'),
      averageLatencyMs: t(locale, 'processorMetricAverageLatencyMs'),
      maxLatencyMs: t(locale, 'processorMetricMaxLatencyMs'),
    } as Record<string, string>,
    statusLabels: {
      ready: t(locale, 'processorStatusReady'),
      disabled: t(locale, 'processorStatusDisabled'),
      unavailable: t(locale, 'processorStatusUnavailable'),
      degraded: t(locale, 'processorStatusDegraded'),
      'circuit-open': t(locale, 'processorStatusCircuitOpen'),
    } as Record<ProcessorStatusEntry['status'], string>,
  };
}
